FROM node:24-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install ALL dependencies (including devDependencies for nodemon)
RUN npm install

EXPOSE 3000

# Use nodemon for development
CMD ["npm", "run", "dev"]